version: "3.8"

services:
  # ==================== PostgreSQL Database Service ====================
  postgres:
    image: postgres:16-alpine
    container_name: fastapi_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # ==================== FastAPI Application Service ====================
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi_app
    env_file:
      - .env
    environment:
      # Override to use Docker service name
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      # Mount source code for hot reload (development)
      - ./app:/app/app:ro
      # Mount logs for persistence
      - ./logs:/app/logs
      # Mount migrations (optional, for development)
      - ./migrations:/app/migrations:ro
    networks:
      - fastapi_network
    depends_on:
      postgres:
        condition: service_healthy
    # Development-friendly command with hot reload
    command: >
      uvicorn app.core.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/app
      --log-level ${LOG_LEVEL:-info}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

# ==================== Networks ====================
networks:
  fastapi_network:
    driver: bridge
    name: fastapi_network

# ==================== Volumes ====================
volumes:
  postgres_data:
    name: fastapi_postgres_data
